add basic example with User class that persist with mongodb
dusktreader/flask-praetorian pull request #204
Opened 2020-06-06 16:00 UTC by christofer-f

Hi,

I am very new to GIT so I am not sure if I do this right...
Since I will use this excellent library I thought to do a small contribution.

Br,
Christofer

2020-06-10 06:28 UTC, dusktreader commented
@christofer-f Thanks for the contribution! I have two comments for you to address above. Looking forward to including this example in the next release.

2020-06-10 08:45 UTC, christofer-f commented
I am very new to git and trying to do the changes in a branch... 
I will try to include the tests you require.
It seems that I have created an unintended commit... 
It a little of a mess here...
Sorry

2020-06-10 21:42 UTC, dusktreader requested changes

2020-06-11 05:25 UTC, dusktreader commented on example/basic_mongo.py
> +    # curl http://localhost:5000/login -X POST -d '{"username":"Walter","password":"calmerthanyouare"}
I fixed this in a new commit on master in your fork. I also reset the master branch back to your original commit.

2020-06-11 05:26 UTC, dusktreader approved these changes

2020-06-11 05:40 UTC, merged